export default function Cards() {
  return (
    <div className="cards">
      <div>
        <picture></picture>
        <p>haha</p>
      </div>
      <div>
        <picture></picture>
        <p>haha</p>
      </div>
      <div>
        <picture></picture>
        <p>haha</p>
      </div>
      <div>
        <picture></picture>
        <p>haha</p>
      </div>
      <div>
        <picture></picture>
        <p>haha</p>
      </div>
      <div>
        <picture></picture>
        <p>haha</p>
      </div>
      <div>
        <picture></picture>
        <p>haha</p>
      </div>
      <div>
        <picture></picture>
        <p>haha</p>
      </div>
      <div>
        <picture></picture>
        <p>haha</p>
      </div>
      <div>
        <picture></picture>
        <p>haha</p>
      </div>
      <div>
        <picture></picture>
        <p>haha</p>
      </div>
    </div>
  );
}
